"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from compass_api_sdk.types import BaseModel
import pydantic
from pydantic import ConfigDict
from typing import Any, Dict, Union
from typing_extensions import TypeAliasType, TypedDict


PendleBuyPtParamsAmountTypedDict = TypeAliasType(
    "PendleBuyPtParamsAmountTypedDict", Union[float, str]
)
r"""The amount of market's Underlying Token you would like to sell for market's Principal Token (PT)."""


PendleBuyPtParamsAmount = TypeAliasType("PendleBuyPtParamsAmount", Union[float, str])
r"""The amount of market's Underlying Token you would like to sell for market's Principal Token (PT)."""


class PendleBuyPtParamsTypedDict(TypedDict):
    market_address: str
    r"""The address of the market identifying which Principal Token (PT) you would like to buy."""
    amount: PendleBuyPtParamsAmountTypedDict
    r"""The amount of market's Underlying Token you would like to sell for market's Principal Token (PT)."""


class PendleBuyPtParams(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, Any] = pydantic.Field(init=False)

    market_address: str
    r"""The address of the market identifying which Principal Token (PT) you would like to buy."""

    amount: PendleBuyPtParamsAmount
    r"""The amount of market's Underlying Token you would like to sell for market's Principal Token (PT)."""

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]
