"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .chain import Chain
from compass_api_sdk.types import BaseModel
from typing import Union
from typing_extensions import TypeAliasType, TypedDict


PendleBuyPtRequestAmountTypedDict = TypeAliasType(
    "PendleBuyPtRequestAmountTypedDict", Union[float, str]
)
r"""The amount of market's Underlying Token you would like to sell for market's Principal Token (PT)."""


PendleBuyPtRequestAmount = TypeAliasType("PendleBuyPtRequestAmount", Union[float, str])
r"""The amount of market's Underlying Token you would like to sell for market's Principal Token (PT)."""


class PendleBuyPtRequestTypedDict(TypedDict):
    market_address: str
    r"""The address of the market identifying which Principal Token (PT) you would like to buy."""
    amount: PendleBuyPtRequestAmountTypedDict
    r"""The amount of market's Underlying Token you would like to sell for market's Principal Token (PT)."""
    chain: Chain
    r"""The chain to use."""
    sender: str
    r"""The address of the transaction sender."""


class PendleBuyPtRequest(BaseModel):
    market_address: str
    r"""The address of the market identifying which Principal Token (PT) you would like to buy."""

    amount: PendleBuyPtRequestAmount
    r"""The amount of market's Underlying Token you would like to sell for market's Principal Token (PT)."""

    chain: Chain
    r"""The chain to use."""

    sender: str
    r"""The address of the transaction sender."""
