#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2502-2-ged9d49af"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2502
#define NETGEN_VERSION_TWEAK 2
#define NETGEN_VERSION_HASH "ged9d49af"
#endif // NETGEN_VERSION_HPP_INCLUDED
