# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing_extensions
import typing
from ...core.serialization import FieldMetadata
from .decimal import Decimal
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class AgentSetting(UniversalBaseModel):
    """
    The settings for the agent.
    """

    name: str = pydantic.Field()
    """
    The setting name.
    """

    value_string: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="valueString")
    ] = pydantic.Field(default=None)
    """
    The setting value.
    """

    value_boolean: typing_extensions.Annotated[
        typing.Optional[bool], FieldMetadata(alias="valueBoolean")
    ] = pydantic.Field(default=None)
    """
    The setting value.
    """

    value_decimal: typing_extensions.Annotated[
        typing.Optional[Decimal], FieldMetadata(alias="valueDecimal")
    ] = pydantic.Field(default=None)
    """
    The setting value.
    """

    value_integer: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="valueInteger")
    ] = pydantic.Field(default=None)
    """
    The setting value.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
