# This file was auto-generated by Fern from our API Definition.

import typing

PlanDefinitionParticipantType = typing.Union[
    typing.Literal["patient", "practitioner", "related-person", "device"], typing.Any
]
