
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-06-03T15:45:25-0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "2c58fc8696c47cf695b2beb925ac37c9ff867299",
 "version": "2.62.1b2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
