# Generated by Django 5.1.7 on 2025-03-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
