# coding: utf-8

"""
    Graphiant APIs

    **To use the APIs:**   1) Login using /api/v1/auth/login   2) Copy the value of \"token\" in the response   3) Click the \"Authorize\" button   4) In the \"Value\" text field enter: \"Bearer &lt;paste token from login api response&gt;\"   5) Click \"Authorize\"   6) If a valid token was entered, all requests are now authorized    **The token is valid for 2 hours, if it's expired (403 response from apis):**  1) Login again using the login api  2) Click \"Authorize\"  3) Click \"Logout\" and enter the new token just as before  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse200239SiteStatus(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'status': 'str',
        'statuses': 'list[InlineResponse200239SiteStatusStatuses]'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'status': 'status',
        'statuses': 'statuses'
    }

    def __init__(self, id=None, name=None, status=None, statuses=None):  # noqa: E501
        """InlineResponse200239SiteStatus - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._status = None
        self._statuses = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if status is not None:
            self.status = status
        if statuses is not None:
            self.statuses = statuses

    @property
    def id(self):
        """Gets the id of this InlineResponse200239SiteStatus.  # noqa: E501


        :return: The id of this InlineResponse200239SiteStatus.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InlineResponse200239SiteStatus.


        :param id: The id of this InlineResponse200239SiteStatus.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this InlineResponse200239SiteStatus.  # noqa: E501


        :return: The name of this InlineResponse200239SiteStatus.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this InlineResponse200239SiteStatus.


        :param name: The name of this InlineResponse200239SiteStatus.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def status(self):
        """Gets the status of this InlineResponse200239SiteStatus.  # noqa: E501


        :return: The status of this InlineResponse200239SiteStatus.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this InlineResponse200239SiteStatus.


        :param status: The status of this InlineResponse200239SiteStatus.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def statuses(self):
        """Gets the statuses of this InlineResponse200239SiteStatus.  # noqa: E501


        :return: The statuses of this InlineResponse200239SiteStatus.  # noqa: E501
        :rtype: list[InlineResponse200239SiteStatusStatuses]
        """
        return self._statuses

    @statuses.setter
    def statuses(self, statuses):
        """Sets the statuses of this InlineResponse200239SiteStatus.


        :param statuses: The statuses of this InlineResponse200239SiteStatus.  # noqa: E501
        :type: list[InlineResponse200239SiteStatusStatuses]
        """

        self._statuses = statuses

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse200239SiteStatus, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse200239SiteStatus):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
