# coding: utf-8

"""
    Graphiant APIs

    **To use the APIs:**   1) Login using /api/v1/auth/login   2) Copy the value of \"token\" in the response   3) Click the \"Authorize\" button   4) In the \"Value\" text field enter: \"Bearer &lt;paste token from login api response&gt;\"   5) Click \"Authorize\"   6) If a valid token was entered, all requests are now authorized    **The token is valid for 2 hours, if it's expired (403 response from apis):**  1) Login again using the login api  2) Click \"Authorize\"  3) Click \"Logout\" and enter the new token just as before  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse200222SystemPlaneTimeWindow(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'bucket_size_sec': 'str',
        'old_ts': 'object',
        'recent_ts': 'object'
    }

    attribute_map = {
        'bucket_size_sec': 'bucketSizeSec',
        'old_ts': 'oldTs',
        'recent_ts': 'recentTs'
    }

    def __init__(self, bucket_size_sec=None, old_ts=None, recent_ts=None):  # noqa: E501
        """InlineResponse200222SystemPlaneTimeWindow - a model defined in Swagger"""  # noqa: E501
        self._bucket_size_sec = None
        self._old_ts = None
        self._recent_ts = None
        self.discriminator = None
        if bucket_size_sec is not None:
            self.bucket_size_sec = bucket_size_sec
        if old_ts is not None:
            self.old_ts = old_ts
        if recent_ts is not None:
            self.recent_ts = recent_ts

    @property
    def bucket_size_sec(self):
        """Gets the bucket_size_sec of this InlineResponse200222SystemPlaneTimeWindow.  # noqa: E501


        :return: The bucket_size_sec of this InlineResponse200222SystemPlaneTimeWindow.  # noqa: E501
        :rtype: str
        """
        return self._bucket_size_sec

    @bucket_size_sec.setter
    def bucket_size_sec(self, bucket_size_sec):
        """Sets the bucket_size_sec of this InlineResponse200222SystemPlaneTimeWindow.


        :param bucket_size_sec: The bucket_size_sec of this InlineResponse200222SystemPlaneTimeWindow.  # noqa: E501
        :type: str
        """

        self._bucket_size_sec = bucket_size_sec

    @property
    def old_ts(self):
        """Gets the old_ts of this InlineResponse200222SystemPlaneTimeWindow.  # noqa: E501


        :return: The old_ts of this InlineResponse200222SystemPlaneTimeWindow.  # noqa: E501
        :rtype: object
        """
        return self._old_ts

    @old_ts.setter
    def old_ts(self, old_ts):
        """Sets the old_ts of this InlineResponse200222SystemPlaneTimeWindow.


        :param old_ts: The old_ts of this InlineResponse200222SystemPlaneTimeWindow.  # noqa: E501
        :type: object
        """

        self._old_ts = old_ts

    @property
    def recent_ts(self):
        """Gets the recent_ts of this InlineResponse200222SystemPlaneTimeWindow.  # noqa: E501


        :return: The recent_ts of this InlineResponse200222SystemPlaneTimeWindow.  # noqa: E501
        :rtype: object
        """
        return self._recent_ts

    @recent_ts.setter
    def recent_ts(self, recent_ts):
        """Sets the recent_ts of this InlineResponse200222SystemPlaneTimeWindow.


        :param recent_ts: The recent_ts of this InlineResponse200222SystemPlaneTimeWindow.  # noqa: E501
        :type: object
        """

        self._recent_ts = recent_ts

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse200222SystemPlaneTimeWindow, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse200222SystemPlaneTimeWindow):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
