# coding: utf-8

"""
    Graphiant APIs

    **To use the APIs:**   1) Login using /api/v1/auth/login   2) Copy the value of \"token\" in the response   3) Click the \"Authorize\" button   4) In the \"Value\" text field enter: \"Bearer &lt;paste token from login api response&gt;\"   5) Click \"Authorize\"   6) If a valid token was entered, all requests are now authorized    **The token is valid for 2 hours, if it's expired (403 response from apis):**  1) Login again using the login api  2) Click \"Authorize\"  3) Click \"Logout\" and enter the new token just as before  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse200164Ipv4DhcpRelay(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'dhcpv4_relays': 'list[str]',
        'dhcpv6_relays': 'list[str]',
        'id': 'str'
    }

    attribute_map = {
        'dhcpv4_relays': 'dhcpv4Relays',
        'dhcpv6_relays': 'dhcpv6Relays',
        'id': 'id'
    }

    def __init__(self, dhcpv4_relays=None, dhcpv6_relays=None, id=None):  # noqa: E501
        """InlineResponse200164Ipv4DhcpRelay - a model defined in Swagger"""  # noqa: E501
        self._dhcpv4_relays = None
        self._dhcpv6_relays = None
        self._id = None
        self.discriminator = None
        if dhcpv4_relays is not None:
            self.dhcpv4_relays = dhcpv4_relays
        if dhcpv6_relays is not None:
            self.dhcpv6_relays = dhcpv6_relays
        if id is not None:
            self.id = id

    @property
    def dhcpv4_relays(self):
        """Gets the dhcpv4_relays of this InlineResponse200164Ipv4DhcpRelay.  # noqa: E501


        :return: The dhcpv4_relays of this InlineResponse200164Ipv4DhcpRelay.  # noqa: E501
        :rtype: list[str]
        """
        return self._dhcpv4_relays

    @dhcpv4_relays.setter
    def dhcpv4_relays(self, dhcpv4_relays):
        """Sets the dhcpv4_relays of this InlineResponse200164Ipv4DhcpRelay.


        :param dhcpv4_relays: The dhcpv4_relays of this InlineResponse200164Ipv4DhcpRelay.  # noqa: E501
        :type: list[str]
        """

        self._dhcpv4_relays = dhcpv4_relays

    @property
    def dhcpv6_relays(self):
        """Gets the dhcpv6_relays of this InlineResponse200164Ipv4DhcpRelay.  # noqa: E501


        :return: The dhcpv6_relays of this InlineResponse200164Ipv4DhcpRelay.  # noqa: E501
        :rtype: list[str]
        """
        return self._dhcpv6_relays

    @dhcpv6_relays.setter
    def dhcpv6_relays(self, dhcpv6_relays):
        """Sets the dhcpv6_relays of this InlineResponse200164Ipv4DhcpRelay.


        :param dhcpv6_relays: The dhcpv6_relays of this InlineResponse200164Ipv4DhcpRelay.  # noqa: E501
        :type: list[str]
        """

        self._dhcpv6_relays = dhcpv6_relays

    @property
    def id(self):
        """Gets the id of this InlineResponse200164Ipv4DhcpRelay.  # noqa: E501


        :return: The id of this InlineResponse200164Ipv4DhcpRelay.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InlineResponse200164Ipv4DhcpRelay.


        :param id: The id of this InlineResponse200164Ipv4DhcpRelay.  # noqa: E501
        :type: str
        """

        self._id = id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse200164Ipv4DhcpRelay, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse200164Ipv4DhcpRelay):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
