from .model import *
from .evaluate import *
from .generate_interpretations import *
from .get_variables import *
from .get_variables import *
from .is_satisfiable import *
from .modus_ponens import *
from .print_formula import *
from .print_truth_table import *
from .substitute import *
from .to_pnf import *
from .unify import *
from .universal_instantiation import *
