# This file was auto-generated by Fern from our API Definition.

import typing

StructureMapSourceListMode = typing.Union[
    typing.Literal["first", "not_first", "last", "not_last", "only_one"], typing.Any
]
