
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-06-03T22:34:22+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "5805c5b4f69d25c99b66f00b93e59e6e3949a429",
 "version": "2.5.0.dev1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
