# coding: utf-8

"""
    Platform External API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from platform_api_python_client.models.ticket_priority import TicketPriority

class TestTicketPriority(unittest.TestCase):
    """TicketPriority unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTicketPriority(self):
        """Test TicketPriority"""
        # inst = TicketPriority()

if __name__ == '__main__':
    unittest.main()
