import amsdal_glue as glue
from _typeshed import Incomplete
from amsdal_data.connections.historical.command_builder import async_build_historical_table_name as async_build_historical_table_name, build_historical_table_name as build_historical_table_name

class _TableNameTransform:
    query: Incomplete
    def __init__(self, query: glue.QueryStatement) -> None: ...
    @property
    def table_name(self) -> str: ...
    def _resolve_table_name(self, query: glue.QueryStatement) -> str: ...

class TableNameTransform(_TableNameTransform):
    def transform(self) -> glue.QueryStatement: ...
    @classmethod
    def _process_table_names(cls, query: glue.QueryStatement) -> glue.QueryStatement: ...
    @classmethod
    def process_table_name(cls, table: glue.SchemaReference | glue.SubQueryStatement) -> None: ...

class AsyncTableNameTransform(_TableNameTransform):
    async def transform(self) -> glue.QueryStatement: ...
    @classmethod
    async def _process_table_names(cls, query: glue.QueryStatement) -> glue.QueryStatement: ...
    @classmethod
    async def process_table_name(cls, table: glue.SchemaReference | glue.SubQueryStatement) -> None: ...
