# coding: utf-8

"""
    Graphiant APIs

    **To use the APIs:**   1) Login using /api/v1/auth/login   2) Copy the value of \"token\" in the response   3) Click the \"Authorize\" button   4) In the \"Value\" text field enter: \"Bearer &lt;paste token from login api response&gt;\"   5) Click \"Authorize\"   6) If a valid token was entered, all requests are now authorized    **The token is valid for 2 hours, if it's expired (403 response from apis):**  1) Login again using the login api  2) Click \"Authorize\"  3) Click \"Logout\" and enter the new token just as before  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse200234Connections(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'active': 'str',
        'circuit_carrier': 'str',
        'circuit_name': 'str',
        'destination_ip': 'str',
        'hostname': 'str',
        'last_established_time': 'V1devicesbringuptokenValidTillTs',
        'last_resort': 'str',
        'quality': 'str',
        'source_ip': 'str',
        'source_public_ip': 'str'
    }

    attribute_map = {
        'active': 'active',
        'circuit_carrier': 'circuitCarrier',
        'circuit_name': 'circuitName',
        'destination_ip': 'destinationIp',
        'hostname': 'hostname',
        'last_established_time': 'lastEstablishedTime',
        'last_resort': 'lastResort',
        'quality': 'quality',
        'source_ip': 'sourceIp',
        'source_public_ip': 'sourcePublicIp'
    }

    def __init__(self, active=None, circuit_carrier=None, circuit_name=None, destination_ip=None, hostname=None, last_established_time=None, last_resort=None, quality=None, source_ip=None, source_public_ip=None):  # noqa: E501
        """InlineResponse200234Connections - a model defined in Swagger"""  # noqa: E501
        self._active = None
        self._circuit_carrier = None
        self._circuit_name = None
        self._destination_ip = None
        self._hostname = None
        self._last_established_time = None
        self._last_resort = None
        self._quality = None
        self._source_ip = None
        self._source_public_ip = None
        self.discriminator = None
        if active is not None:
            self.active = active
        if circuit_carrier is not None:
            self.circuit_carrier = circuit_carrier
        if circuit_name is not None:
            self.circuit_name = circuit_name
        if destination_ip is not None:
            self.destination_ip = destination_ip
        if hostname is not None:
            self.hostname = hostname
        if last_established_time is not None:
            self.last_established_time = last_established_time
        if last_resort is not None:
            self.last_resort = last_resort
        if quality is not None:
            self.quality = quality
        if source_ip is not None:
            self.source_ip = source_ip
        if source_public_ip is not None:
            self.source_public_ip = source_public_ip

    @property
    def active(self):
        """Gets the active of this InlineResponse200234Connections.  # noqa: E501


        :return: The active of this InlineResponse200234Connections.  # noqa: E501
        :rtype: str
        """
        return self._active

    @active.setter
    def active(self, active):
        """Sets the active of this InlineResponse200234Connections.


        :param active: The active of this InlineResponse200234Connections.  # noqa: E501
        :type: str
        """

        self._active = active

    @property
    def circuit_carrier(self):
        """Gets the circuit_carrier of this InlineResponse200234Connections.  # noqa: E501


        :return: The circuit_carrier of this InlineResponse200234Connections.  # noqa: E501
        :rtype: str
        """
        return self._circuit_carrier

    @circuit_carrier.setter
    def circuit_carrier(self, circuit_carrier):
        """Sets the circuit_carrier of this InlineResponse200234Connections.


        :param circuit_carrier: The circuit_carrier of this InlineResponse200234Connections.  # noqa: E501
        :type: str
        """

        self._circuit_carrier = circuit_carrier

    @property
    def circuit_name(self):
        """Gets the circuit_name of this InlineResponse200234Connections.  # noqa: E501


        :return: The circuit_name of this InlineResponse200234Connections.  # noqa: E501
        :rtype: str
        """
        return self._circuit_name

    @circuit_name.setter
    def circuit_name(self, circuit_name):
        """Sets the circuit_name of this InlineResponse200234Connections.


        :param circuit_name: The circuit_name of this InlineResponse200234Connections.  # noqa: E501
        :type: str
        """

        self._circuit_name = circuit_name

    @property
    def destination_ip(self):
        """Gets the destination_ip of this InlineResponse200234Connections.  # noqa: E501


        :return: The destination_ip of this InlineResponse200234Connections.  # noqa: E501
        :rtype: str
        """
        return self._destination_ip

    @destination_ip.setter
    def destination_ip(self, destination_ip):
        """Sets the destination_ip of this InlineResponse200234Connections.


        :param destination_ip: The destination_ip of this InlineResponse200234Connections.  # noqa: E501
        :type: str
        """

        self._destination_ip = destination_ip

    @property
    def hostname(self):
        """Gets the hostname of this InlineResponse200234Connections.  # noqa: E501


        :return: The hostname of this InlineResponse200234Connections.  # noqa: E501
        :rtype: str
        """
        return self._hostname

    @hostname.setter
    def hostname(self, hostname):
        """Sets the hostname of this InlineResponse200234Connections.


        :param hostname: The hostname of this InlineResponse200234Connections.  # noqa: E501
        :type: str
        """

        self._hostname = hostname

    @property
    def last_established_time(self):
        """Gets the last_established_time of this InlineResponse200234Connections.  # noqa: E501


        :return: The last_established_time of this InlineResponse200234Connections.  # noqa: E501
        :rtype: V1devicesbringuptokenValidTillTs
        """
        return self._last_established_time

    @last_established_time.setter
    def last_established_time(self, last_established_time):
        """Sets the last_established_time of this InlineResponse200234Connections.


        :param last_established_time: The last_established_time of this InlineResponse200234Connections.  # noqa: E501
        :type: V1devicesbringuptokenValidTillTs
        """

        self._last_established_time = last_established_time

    @property
    def last_resort(self):
        """Gets the last_resort of this InlineResponse200234Connections.  # noqa: E501


        :return: The last_resort of this InlineResponse200234Connections.  # noqa: E501
        :rtype: str
        """
        return self._last_resort

    @last_resort.setter
    def last_resort(self, last_resort):
        """Sets the last_resort of this InlineResponse200234Connections.


        :param last_resort: The last_resort of this InlineResponse200234Connections.  # noqa: E501
        :type: str
        """

        self._last_resort = last_resort

    @property
    def quality(self):
        """Gets the quality of this InlineResponse200234Connections.  # noqa: E501


        :return: The quality of this InlineResponse200234Connections.  # noqa: E501
        :rtype: str
        """
        return self._quality

    @quality.setter
    def quality(self, quality):
        """Sets the quality of this InlineResponse200234Connections.


        :param quality: The quality of this InlineResponse200234Connections.  # noqa: E501
        :type: str
        """

        self._quality = quality

    @property
    def source_ip(self):
        """Gets the source_ip of this InlineResponse200234Connections.  # noqa: E501


        :return: The source_ip of this InlineResponse200234Connections.  # noqa: E501
        :rtype: str
        """
        return self._source_ip

    @source_ip.setter
    def source_ip(self, source_ip):
        """Sets the source_ip of this InlineResponse200234Connections.


        :param source_ip: The source_ip of this InlineResponse200234Connections.  # noqa: E501
        :type: str
        """

        self._source_ip = source_ip

    @property
    def source_public_ip(self):
        """Gets the source_public_ip of this InlineResponse200234Connections.  # noqa: E501


        :return: The source_public_ip of this InlineResponse200234Connections.  # noqa: E501
        :rtype: str
        """
        return self._source_public_ip

    @source_public_ip.setter
    def source_public_ip(self, source_public_ip):
        """Sets the source_public_ip of this InlineResponse200234Connections.


        :param source_public_ip: The source_public_ip of this InlineResponse200234Connections.  # noqa: E501
        :type: str
        """

        self._source_public_ip = source_public_ip

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse200234Connections, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse200234Connections):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
