# coding: utf-8

"""
    Graphiant APIs

    **To use the APIs:**   1) Login using /api/v1/auth/login   2) Copy the value of \"token\" in the response   3) Click the \"Authorize\" button   4) In the \"Value\" text field enter: \"Bearer &lt;paste token from login api response&gt;\"   5) Click \"Authorize\"   6) If a valid token was entered, all requests are now authorized    **The token is valid for 2 hours, if it's expired (403 response from apis):**  1) Login again using the login api  2) Click \"Authorize\"  3) Click \"Logout\" and enter the new token just as before  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse20036ScoreDetailsScoreBucketList(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'curr_score': 'str',
        'max_score': 'str',
        'score_bucket_id': 'str'
    }

    attribute_map = {
        'curr_score': 'currScore',
        'max_score': 'maxScore',
        'score_bucket_id': 'scoreBucketId'
    }

    def __init__(self, curr_score=None, max_score=None, score_bucket_id=None):  # noqa: E501
        """InlineResponse20036ScoreDetailsScoreBucketList - a model defined in Swagger"""  # noqa: E501
        self._curr_score = None
        self._max_score = None
        self._score_bucket_id = None
        self.discriminator = None
        if curr_score is not None:
            self.curr_score = curr_score
        if max_score is not None:
            self.max_score = max_score
        if score_bucket_id is not None:
            self.score_bucket_id = score_bucket_id

    @property
    def curr_score(self):
        """Gets the curr_score of this InlineResponse20036ScoreDetailsScoreBucketList.  # noqa: E501


        :return: The curr_score of this InlineResponse20036ScoreDetailsScoreBucketList.  # noqa: E501
        :rtype: str
        """
        return self._curr_score

    @curr_score.setter
    def curr_score(self, curr_score):
        """Sets the curr_score of this InlineResponse20036ScoreDetailsScoreBucketList.


        :param curr_score: The curr_score of this InlineResponse20036ScoreDetailsScoreBucketList.  # noqa: E501
        :type: str
        """

        self._curr_score = curr_score

    @property
    def max_score(self):
        """Gets the max_score of this InlineResponse20036ScoreDetailsScoreBucketList.  # noqa: E501


        :return: The max_score of this InlineResponse20036ScoreDetailsScoreBucketList.  # noqa: E501
        :rtype: str
        """
        return self._max_score

    @max_score.setter
    def max_score(self, max_score):
        """Sets the max_score of this InlineResponse20036ScoreDetailsScoreBucketList.


        :param max_score: The max_score of this InlineResponse20036ScoreDetailsScoreBucketList.  # noqa: E501
        :type: str
        """

        self._max_score = max_score

    @property
    def score_bucket_id(self):
        """Gets the score_bucket_id of this InlineResponse20036ScoreDetailsScoreBucketList.  # noqa: E501


        :return: The score_bucket_id of this InlineResponse20036ScoreDetailsScoreBucketList.  # noqa: E501
        :rtype: str
        """
        return self._score_bucket_id

    @score_bucket_id.setter
    def score_bucket_id(self, score_bucket_id):
        """Sets the score_bucket_id of this InlineResponse20036ScoreDetailsScoreBucketList.


        :param score_bucket_id: The score_bucket_id of this InlineResponse20036ScoreDetailsScoreBucketList.  # noqa: E501
        :type: str
        """

        self._score_bucket_id = score_bucket_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20036ScoreDetailsScoreBucketList, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20036ScoreDetailsScoreBucketList):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
