# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
from .address import Address
from .age import Age
from .annotation import Annotation
from .attachment import Attachment
from .codeable_concept import CodeableConcept
from .coding import Coding
from .contact_detail import ContactDetail
from .contact_point import ContactPoint
from .contributor import Contributor
from .count import Count
from .data_requirement import DataRequirement
from .data_requirement_code_filter import DataRequirementCodeFilter
from .data_requirement_date_filter import DataRequirementDateFilter
from .data_requirement_sort import DataRequirementSort
from .distance import Distance
from .dosage import Dosage
from .dosage_dose_and_rate import DosageDoseAndRate
from .duration import Duration
from .expression import Expression
from .extension import Extension
from .human_name import HumanName
from .identifier import Identifier
from .meta import Meta
from .money import Money
from .parameter_definition import ParameterDefinition
from .period import Period
from .quantity import Quantity
from .range import Range
from .ratio import Ratio
from .reference import Reference
from .related_artifact import RelatedArtifact
from .sampled_data import SampledData
from .signature import Signature
from .timing import Timing
from .timing_repeat import TimingRepeat
from .trigger_definition import TriggerDefinition
from .usage_context import UsageContext
import typing
import pydantic
import typing_extensions
from ...core.serialization import FieldMetadata
from .date_time import DateTime
from .decimal import Decimal
from .unsigned_int import UnsignedInt
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class ContractValuedItem(UniversalBaseModel):
    """
    Legally enforceable, formally recorded unilateral or bilateral directive i.e., a policy or agreement.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.
    """

    extension: typing.Optional[typing.List[Extension]] = pydantic.Field(default=None)
    """
    May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.
    """

    modifier_extension: typing_extensions.Annotated[
        typing.Optional[typing.List[Extension]],
        FieldMetadata(alias="modifierExtension"),
    ] = pydantic.Field(default=None)
    """
    May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the understanding of the containing element's descendants. Usually modifier elements provide negation or qualification. To make the use of extensions safe and manageable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. Applications processing a resource are required to check for modifier extensions. Modifier extensions SHALL NOT change the meaning of any elements on Resource or DomainResource (including cannot change the meaning of modifierExtension itself).
    """

    entity_codeable_concept: typing_extensions.Annotated[
        typing.Optional[CodeableConcept], FieldMetadata(alias="entityCodeableConcept")
    ] = pydantic.Field(default=None)
    """
    Specific type of Contract Valued Item that may be priced.
    """

    entity_reference: typing_extensions.Annotated[
        typing.Optional[Reference], FieldMetadata(alias="entityReference")
    ] = pydantic.Field(default=None)
    """
    Specific type of Contract Valued Item that may be priced.
    """

    identifier: typing.Optional[Identifier] = pydantic.Field(default=None)
    """
    Identifies a Contract Valued Item instance.
    """

    effective_time: typing_extensions.Annotated[
        typing.Optional[DateTime], FieldMetadata(alias="effectiveTime")
    ] = pydantic.Field(default=None)
    """
    Indicates the time during which this Contract ValuedItem information is effective.
    """

    quantity: typing.Optional[Quantity] = pydantic.Field(default=None)
    """
    Specifies the units by which the Contract Valued Item is measured or counted, and quantifies the countable or measurable Contract Valued Item instances.
    """

    unit_price: typing_extensions.Annotated[
        typing.Optional[Money], FieldMetadata(alias="unitPrice")
    ] = pydantic.Field(default=None)
    """
    A Contract Valued Item unit valuation measure.
    """

    factor: typing.Optional[Decimal] = pydantic.Field(default=None)
    """
    A real number that represents a multiplier used in determining the overall value of the Contract Valued Item delivered. The concept of a Factor allows for a discount or surcharge multiplier to be applied to a monetary amount.
    """

    points: typing.Optional[Decimal] = pydantic.Field(default=None)
    """
    An amount that expresses the weighting (based on difficulty, cost and/or resource intensiveness) associated with the Contract Valued Item delivered. The concept of Points allows for assignment of point values for a Contract Valued Item, such that a monetary amount can be assigned to each point.
    """

    net: typing.Optional[Money] = pydantic.Field(default=None)
    """
    Expresses the product of the Contract Valued Item unitQuantity and the unitPriceAmt. For example, the formula: unit Quantity _ unit Price (Cost per Point) _ factor Number \* points = net Amount. Quantity, factor and points are assumed to be 1 if not supplied.
    """

    payment: typing.Optional[str] = pydantic.Field(default=None)
    """
    Terms of valuation.
    """

    payment_date: typing_extensions.Annotated[
        typing.Optional[DateTime], FieldMetadata(alias="paymentDate")
    ] = pydantic.Field(default=None)
    """
    When payment is due.
    """

    responsible: typing.Optional[Reference] = pydantic.Field(default=None)
    """
    Who will make payment.
    """

    recipient: typing.Optional[Reference] = pydantic.Field(default=None)
    """
    Who will receive payment.
    """

    link_id: typing_extensions.Annotated[
        typing.Optional[typing.List[str]], FieldMetadata(alias="linkId")
    ] = pydantic.Field(default=None)
    """
    Id of the clause or question text related to the context of this valuedItem in the referenced form or QuestionnaireResponse.
    """

    security_label_number: typing_extensions.Annotated[
        typing.Optional[typing.List[UnsignedInt]],
        FieldMetadata(alias="securityLabelNumber"),
    ] = pydantic.Field(default=None)
    """
    A set of security labels that define which terms are controlled by this condition.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
