# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: arg_services/ranking/v1beta/granularity.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'arg_services/ranking/v1beta/granularity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-arg_services/ranking/v1beta/granularity.proto\x12\x1b\x61rg_services.ranking.v1beta\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\"z\n\x1d\x46ineGranularClusteringRequest\x12\x14\n\x05query\x18\x01 \x01(\tR\x05query\x12\x12\n\x04\x61\x64us\x18\x02 \x03(\tR\x04\x61\x64us\x12/\n\x06\x65xtras\x18\x0f \x01(\x0b\x32\x17.google.protobuf.StructR\x06\x65xtras\"\xa7\x01\n\x1e\x46ineGranularClusteringResponse\x12T\n\x0bpredictions\x18\x01 \x03(\x0b\x32\x32.arg_services.ranking.v1beta.GranularityPredictionR\x0bpredictions\x12/\n\x06\x65xtras\x18\x0f \x01(\x0b\x32\x17.google.protobuf.StructR\x06\x65xtras\"\x7f\n\x15GranularityPrediction\x12\x16\n\x06stance\x18\x01 \x01(\x01R\x06stance\x12\x14\n\x05\x66rame\x18\x02 \x01(\x01R\x05\x66rame\x12\x18\n\x07meaning\x18\x03 \x01(\x01R\x07meaning\x12\x1e\n\nhierarchic\x18\x04 \x01(\x01R\nhierarchic2\xdd\x01\n\x12GranularityService\x12\xc6\x01\n\x16\x46ineGranularClustering\x12:.arg_services.ranking.v1beta.FineGranularClusteringRequest\x1a;.arg_services.ranking.v1beta.FineGranularClusteringResponse\"3\x82\xd3\xe4\x93\x02-\"(/ranking/v1beta/fine_granular_clustering:\x01*B\xbd\x01\n\x1f\x63om.arg_services.ranking.v1betaB\x10GranularityProtoP\x01\xa2\x02\x03\x41RX\xaa\x02\x1a\x41rgServices.Ranking.V1beta\xca\x02\x1a\x41rgServices\\Ranking\\V1beta\xe2\x02&ArgServices\\Ranking\\V1beta\\GPBMetadata\xea\x02\x1c\x41rgServices::Ranking::V1betab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'arg_services.ranking.v1beta.granularity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\037com.arg_services.ranking.v1betaB\020GranularityProtoP\001\242\002\003ARX\252\002\032ArgServices.Ranking.V1beta\312\002\032ArgServices\\Ranking\\V1beta\342\002&ArgServices\\Ranking\\V1beta\\GPBMetadata\352\002\034ArgServices::Ranking::V1beta'
  _globals['_GRANULARITYSERVICE'].methods_by_name['FineGranularClustering']._loaded_options = None
  _globals['_GRANULARITYSERVICE'].methods_by_name['FineGranularClustering']._serialized_options = b'\202\323\344\223\002-\"(/ranking/v1beta/fine_granular_clustering:\001*'
  _globals['_FINEGRANULARCLUSTERINGREQUEST']._serialized_start=138
  _globals['_FINEGRANULARCLUSTERINGREQUEST']._serialized_end=260
  _globals['_FINEGRANULARCLUSTERINGRESPONSE']._serialized_start=263
  _globals['_FINEGRANULARCLUSTERINGRESPONSE']._serialized_end=430
  _globals['_GRANULARITYPREDICTION']._serialized_start=432
  _globals['_GRANULARITYPREDICTION']._serialized_end=559
  _globals['_GRANULARITYSERVICE']._serialized_start=562
  _globals['_GRANULARITYSERVICE']._serialized_end=783
# @@protoc_insertion_point(module_scope)
