# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: arg_services/cbr/v1beta/casebase.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'arg_services/cbr/v1beta/casebase.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from arg_services.cbr.v1beta import model_pb2 as arg__services_dot_cbr_dot_v1beta_dot_model__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&arg_services/cbr/v1beta/casebase.proto\x12\x17\x61rg_services.cbr.v1beta\x1a#arg_services/cbr/v1beta/model.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xc8\x01\n\x0f\x43\x61sebaseRequest\x12\x41\n\x07include\x18\x01 \x01(\x0b\x32\'.arg_services.cbr.v1beta.CasebaseFilterR\x07include\x12\x41\n\x07\x65xclude\x18\x02 \x01(\x0b\x32\'.arg_services.cbr.v1beta.CasebaseFilterR\x07\x65xclude\x12/\n\x06\x65xtras\x18\x0f \x01(\x0b\x32\x17.google.protobuf.StructR\x06\x65xtras\"\xc1\x01\n\x10\x43\x61sebaseResponse\x12J\n\x05\x63\x61ses\x18\x01 \x03(\x0b\x32\x34.arg_services.cbr.v1beta.CasebaseResponse.CasesEntryR\x05\x63\x61ses\x1a\x61\n\nCasesEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12=\n\x05value\x18\x02 \x01(\x0b\x32\'.arg_services.cbr.v1beta.AnnotatedGraphR\x05value:\x02\x38\x01\x32\x94\x01\n\x0f\x43\x61sebaseService\x12\x80\x01\n\x08\x43\x61sebase\x12(.arg_services.cbr.v1beta.CasebaseRequest\x1a).arg_services.cbr.v1beta.CasebaseResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\"\x14/cbr/v1beta/casebase:\x01*B\xa6\x01\n\x1b\x63om.arg_services.cbr.v1betaB\rCasebaseProtoP\x01\xa2\x02\x03\x41\x43X\xaa\x02\x16\x41rgServices.Cbr.V1beta\xca\x02\x16\x41rgServices\\Cbr\\V1beta\xe2\x02\"ArgServices\\Cbr\\V1beta\\GPBMetadata\xea\x02\x18\x41rgServices::Cbr::V1betab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'arg_services.cbr.v1beta.casebase_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.arg_services.cbr.v1betaB\rCasebaseProtoP\001\242\002\003ACX\252\002\026ArgServices.Cbr.V1beta\312\002\026ArgServices\\Cbr\\V1beta\342\002\"ArgServices\\Cbr\\V1beta\\GPBMetadata\352\002\030ArgServices::Cbr::V1beta'
  _globals['_CASEBASERESPONSE_CASESENTRY']._loaded_options = None
  _globals['_CASEBASERESPONSE_CASESENTRY']._serialized_options = b'8\001'
  _globals['_CASEBASESERVICE'].methods_by_name['Casebase']._loaded_options = None
  _globals['_CASEBASESERVICE'].methods_by_name['Casebase']._serialized_options = b'\202\323\344\223\002\031\"\024/cbr/v1beta/casebase:\001*'
  _globals['_CASEBASEREQUEST']._serialized_start=165
  _globals['_CASEBASEREQUEST']._serialized_end=365
  _globals['_CASEBASERESPONSE']._serialized_start=368
  _globals['_CASEBASERESPONSE']._serialized_end=561
  _globals['_CASEBASERESPONSE_CASESENTRY']._serialized_start=464
  _globals['_CASEBASERESPONSE_CASESENTRY']._serialized_end=561
  _globals['_CASEBASESERVICE']._serialized_start=564
  _globals['_CASEBASESERVICE']._serialized_end=712
# @@protoc_insertion_point(module_scope)
