"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import arg_services.quality.v1beta.qualia_pb2
import collections.abc
import grpc
import grpc.aio
import typing

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

class QualiaServiceStub:
    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    QualiaAnnotations: grpc.UnaryUnaryMultiCallable[
        arg_services.quality.v1beta.qualia_pb2.QualiaAnnotationsRequest,
        arg_services.quality.v1beta.qualia_pb2.QualiaAnnotationsResponse,
    ]

class QualiaServiceAsyncStub:
    QualiaAnnotations: grpc.aio.UnaryUnaryMultiCallable[
        arg_services.quality.v1beta.qualia_pb2.QualiaAnnotationsRequest,
        arg_services.quality.v1beta.qualia_pb2.QualiaAnnotationsResponse,
    ]

class QualiaServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def QualiaAnnotations(
        self,
        request: arg_services.quality.v1beta.qualia_pb2.QualiaAnnotationsRequest,
        context: _ServicerContext,
    ) -> typing.Union[arg_services.quality.v1beta.qualia_pb2.QualiaAnnotationsResponse, collections.abc.Awaitable[arg_services.quality.v1beta.qualia_pb2.QualiaAnnotationsResponse]]: ...

def add_QualiaServiceServicer_to_server(servicer: QualiaServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
