# coding: utf-8

"""
    BMLT

    BMLT Admin API Documentation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bmlt_client.models.user_partial_update import UserPartialUpdate

class TestUserPartialUpdate(unittest.TestCase):
    """UserPartialUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserPartialUpdate:
        """Test UserPartialUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserPartialUpdate`
        """
        model = UserPartialUpdate()
        if include_optional:
            return UserPartialUpdate(
                username = 'string',
                type = 'string',
                display_name = 'string',
                description = 'string',
                email = 'string',
                owner_id = 0,
                password = 'string'
            )
        else:
            return UserPartialUpdate(
        )
        """

    def testUserPartialUpdate(self):
        """Test UserPartialUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
