# Generated by Django 5.1.6 on 2025-04-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rol_usuario',
            field=models.CharField(choices=[('profesor', 'Profesor'), ('director', 'Director'), ('estudiante', 'Estudiante'), ('usuario_normal', 'Usuario normal')], default='usuario_normal', max_length=20),
        ),
    ]
