class PromptimusError(Exception): ...


class ProviderNotSet(PromptimusError): ...


class EmbedderNotSet(PromptimusError): ...


class ParamNotSet(PromptimusError): ...


class FailedToParseOutput(PromptimusError): ...


class MaxIterExceeded(PromptimusError): ...


class InvalidToolName(PromptimusError): ...


class ProviderRetryExceded(PromptimusError): ...
