from .Mat4 import Mat4
from .Vec3 import Vec3

class TransformRotationOrder(Exception): ...

class Transform:
    position: Vec3
    rotation: Vec3
    scale: Vec3
    matrix: Mat4
    need_recalc: bool
    order: str
    rot_order: dict
    def __init__(self) -> None: ...
    def set_position(self, *args) -> None: ...
    def set_rotation(self, *args) -> None: ...
    def set_scale(self, *args) -> None: ...
    def get_matrix(self) -> Mat4: ...
    def set_order(self, order: str): ...
