from typing import Union

from .Mat2 import Mat2

class Vec2:
    x: float
    y: float
    def __init__(self, x: float = ..., y: float = ... ...) -> None: ...
    def __add__(self, rhs: Vec2) -> Vec2: ...
    def __iadd__(self, rhs: Vec2) -> Vec2: ...
    def __sub__(self, rhs: Vec2) -> Vec2: ...
    def __isub__(self, rhs: Vec2) -> Vec2: ...
    def __eq__(self, rhs: object) -> bool: ...
    def __neq__(self, rhs: object) -> bool: ...
    def __neg__(self) -> Vec2: ...
    def set(self, x: float, y: float, ): ...
    def dot(self, rhs: Vec2) -> float: ...
    def length(self) -> float: ...
    def length_squared(self) -> float: ...
    def inner(self, rhs: Vec2) -> float: ...
    def null(self) -> None: ...
    def cross(self, rhs: Vec2) -> Vec2: ...
    def normalize(self) -> None: ...
    def reflect(self, n: Vec2) -> Vec2: ...
    def clamp(self, low: float, high: float): ...
    def outer(self, rhs: Vec2) -> Mat3: ...
    def __mul__(self, rhs: Union[float, int]) -> Vec2: ...
    def __rmul__(self, rhs: Union[float, int]) -> Vec2: ...
    def __matmul__(self, rhs: Mat3) -> Vec2: ...
