"""
Constants for streamlit_permalink.
"""

EMPTY_LIST_URL_VALUE = "_STREAMLIT_PERMALINK_EMPTY"
NONE_URL_VALUE = "_STREAMLIT_PERMALINK_NONE"
EMPTY_STRING_URL_VALUE = "_STREAMLIT_PERMALINK_EMPTY_STRING"
DATAEDITOR_DATE_VALUE_PREFIX = "STREAMLIT_DATE_"
DATAEDITOR_DATETIME_VALUE_PREFIX = "STREAMLIT_DATETIME_"
DATAEDITOR_TIME_VALUE_PREFIX = "STREAMLIT_TIME_"
DATAEDITOR_PREFIX = "STREAMLIT_PERMALINK_DATA_EDITOR_"
DATAEDITOR_COLUMN_CONFIG_PREFIX = "STREAMLIT_PERMALINK_DATA_EDITOR_COLUMN_CONFIG_"
TRUE_URL_VALUE = "True"
FALSE_URL_VALUE = "False"

_BOOL_URL_VALUES = {TRUE_URL_VALUE, FALSE_URL_VALUE}
