class AnacondaAssistantError(Exception): ...


class NotAcceptedTermsError(AnacondaAssistantError): ...


class UnspecifiedAcceptedTermsError(AnacondaAssistantError): ...


class UnspecifiedDataCollectionChoice(AnacondaAssistantError): ...


class DailyQuotaExceeded(AnacondaAssistantError): ...
