# coding: utf-8

"""
    Graphiant APIs

    **To use the APIs:**   1) Login using /api/v1/auth/login   2) Copy the value of \"token\" in the response   3) Click the \"Authorize\" button   4) In the \"Value\" text field enter: \"Bearer &lt;paste token from login api response&gt;\"   5) Click \"Authorize\"   6) If a valid token was entered, all requests are now authorized    **The token is valid for 2 hours, if it's expired (403 response from apis):**  1) Login again using the login api  2) Click \"Authorize\"  3) Click \"Logout\" and enter the new token just as before  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse200222DataPlane(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'down_transitions': 'list[InlineResponse200222DataPlaneDownTransitions]',
        'session_slas': 'list[InlineResponse200222DataPlaneSessionSlas]',
        'status': 'str'
    }

    attribute_map = {
        'down_transitions': 'downTransitions',
        'session_slas': 'sessionSlas',
        'status': 'status'
    }

    def __init__(self, down_transitions=None, session_slas=None, status=None):  # noqa: E501
        """InlineResponse200222DataPlane - a model defined in Swagger"""  # noqa: E501
        self._down_transitions = None
        self._session_slas = None
        self._status = None
        self.discriminator = None
        if down_transitions is not None:
            self.down_transitions = down_transitions
        if session_slas is not None:
            self.session_slas = session_slas
        if status is not None:
            self.status = status

    @property
    def down_transitions(self):
        """Gets the down_transitions of this InlineResponse200222DataPlane.  # noqa: E501


        :return: The down_transitions of this InlineResponse200222DataPlane.  # noqa: E501
        :rtype: list[InlineResponse200222DataPlaneDownTransitions]
        """
        return self._down_transitions

    @down_transitions.setter
    def down_transitions(self, down_transitions):
        """Sets the down_transitions of this InlineResponse200222DataPlane.


        :param down_transitions: The down_transitions of this InlineResponse200222DataPlane.  # noqa: E501
        :type: list[InlineResponse200222DataPlaneDownTransitions]
        """

        self._down_transitions = down_transitions

    @property
    def session_slas(self):
        """Gets the session_slas of this InlineResponse200222DataPlane.  # noqa: E501


        :return: The session_slas of this InlineResponse200222DataPlane.  # noqa: E501
        :rtype: list[InlineResponse200222DataPlaneSessionSlas]
        """
        return self._session_slas

    @session_slas.setter
    def session_slas(self, session_slas):
        """Sets the session_slas of this InlineResponse200222DataPlane.


        :param session_slas: The session_slas of this InlineResponse200222DataPlane.  # noqa: E501
        :type: list[InlineResponse200222DataPlaneSessionSlas]
        """

        self._session_slas = session_slas

    @property
    def status(self):
        """Gets the status of this InlineResponse200222DataPlane.  # noqa: E501


        :return: The status of this InlineResponse200222DataPlane.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this InlineResponse200222DataPlane.


        :param status: The status of this InlineResponse200222DataPlane.  # noqa: E501
        :type: str
        """

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse200222DataPlane, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse200222DataPlane):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
