"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class SortDirection(str, Enum):
    r"""Sort direction options."""

    ASC = "asc"
    DESC = "desc"
