# coding: utf-8

"""
    Graphiant APIs

    **To use the APIs:**   1) Login using /api/v1/auth/login   2) Copy the value of \"token\" in the response   3) Click the \"Authorize\" button   4) In the \"Value\" text field enter: \"Bearer &lt;paste token from login api response&gt;\"   5) Click \"Authorize\"   6) If a valid token was entered, all requests are now authorized    **The token is valid for 2 hours, if it's expired (403 response from apis):**  1) Login again using the login api  2) Click \"Authorize\"  3) Click \"Logout\" and enter the new token just as before  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse200222SystemPlaneCpu(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'interface_name': 'str',
        'peer_name': 'str',
        'time': 'V1devicesbringuptokenValidTillTs',
        'value': 'str'
    }

    attribute_map = {
        'interface_name': 'interfaceName',
        'peer_name': 'peerName',
        'time': 'time',
        'value': 'value'
    }

    def __init__(self, interface_name=None, peer_name=None, time=None, value=None):  # noqa: E501
        """InlineResponse200222SystemPlaneCpu - a model defined in Swagger"""  # noqa: E501
        self._interface_name = None
        self._peer_name = None
        self._time = None
        self._value = None
        self.discriminator = None
        if interface_name is not None:
            self.interface_name = interface_name
        if peer_name is not None:
            self.peer_name = peer_name
        if time is not None:
            self.time = time
        if value is not None:
            self.value = value

    @property
    def interface_name(self):
        """Gets the interface_name of this InlineResponse200222SystemPlaneCpu.  # noqa: E501


        :return: The interface_name of this InlineResponse200222SystemPlaneCpu.  # noqa: E501
        :rtype: str
        """
        return self._interface_name

    @interface_name.setter
    def interface_name(self, interface_name):
        """Sets the interface_name of this InlineResponse200222SystemPlaneCpu.


        :param interface_name: The interface_name of this InlineResponse200222SystemPlaneCpu.  # noqa: E501
        :type: str
        """

        self._interface_name = interface_name

    @property
    def peer_name(self):
        """Gets the peer_name of this InlineResponse200222SystemPlaneCpu.  # noqa: E501


        :return: The peer_name of this InlineResponse200222SystemPlaneCpu.  # noqa: E501
        :rtype: str
        """
        return self._peer_name

    @peer_name.setter
    def peer_name(self, peer_name):
        """Sets the peer_name of this InlineResponse200222SystemPlaneCpu.


        :param peer_name: The peer_name of this InlineResponse200222SystemPlaneCpu.  # noqa: E501
        :type: str
        """

        self._peer_name = peer_name

    @property
    def time(self):
        """Gets the time of this InlineResponse200222SystemPlaneCpu.  # noqa: E501


        :return: The time of this InlineResponse200222SystemPlaneCpu.  # noqa: E501
        :rtype: V1devicesbringuptokenValidTillTs
        """
        return self._time

    @time.setter
    def time(self, time):
        """Sets the time of this InlineResponse200222SystemPlaneCpu.


        :param time: The time of this InlineResponse200222SystemPlaneCpu.  # noqa: E501
        :type: V1devicesbringuptokenValidTillTs
        """

        self._time = time

    @property
    def value(self):
        """Gets the value of this InlineResponse200222SystemPlaneCpu.  # noqa: E501


        :return: The value of this InlineResponse200222SystemPlaneCpu.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this InlineResponse200222SystemPlaneCpu.


        :param value: The value of this InlineResponse200222SystemPlaneCpu.  # noqa: E501
        :type: str
        """

        self._value = value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse200222SystemPlaneCpu, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse200222SystemPlaneCpu):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
