# coding: utf-8

"""
    Graphiant APIs

    **To use the APIs:**   1) Login using /api/v1/auth/login   2) Copy the value of \"token\" in the response   3) Click the \"Authorize\" button   4) In the \"Value\" text field enter: \"Bearer &lt;paste token from login api response&gt;\"   5) Click \"Authorize\"   6) If a valid token was entered, all requests are now authorized    **The token is valid for 2 hours, if it's expired (403 response from apis):**  1) Login again using the login api  2) Click \"Authorize\"  3) Click \"Logout\" and enter the new token just as before  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V2monitoringsitetwampsiteIdSelectors(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'circuit_name': 'str',
        'device_id': 'str',
        'interface_name': 'str',
        'type': 'str'
    }

    attribute_map = {
        'circuit_name': 'circuitName',
        'device_id': 'deviceId',
        'interface_name': 'interfaceName',
        'type': 'type'
    }

    def __init__(self, circuit_name=None, device_id=None, interface_name=None, type=None):  # noqa: E501
        """V2monitoringsitetwampsiteIdSelectors - a model defined in Swagger"""  # noqa: E501
        self._circuit_name = None
        self._device_id = None
        self._interface_name = None
        self._type = None
        self.discriminator = None
        if circuit_name is not None:
            self.circuit_name = circuit_name
        if device_id is not None:
            self.device_id = device_id
        if interface_name is not None:
            self.interface_name = interface_name
        if type is not None:
            self.type = type

    @property
    def circuit_name(self):
        """Gets the circuit_name of this V2monitoringsitetwampsiteIdSelectors.  # noqa: E501


        :return: The circuit_name of this V2monitoringsitetwampsiteIdSelectors.  # noqa: E501
        :rtype: str
        """
        return self._circuit_name

    @circuit_name.setter
    def circuit_name(self, circuit_name):
        """Sets the circuit_name of this V2monitoringsitetwampsiteIdSelectors.


        :param circuit_name: The circuit_name of this V2monitoringsitetwampsiteIdSelectors.  # noqa: E501
        :type: str
        """

        self._circuit_name = circuit_name

    @property
    def device_id(self):
        """Gets the device_id of this V2monitoringsitetwampsiteIdSelectors.  # noqa: E501


        :return: The device_id of this V2monitoringsitetwampsiteIdSelectors.  # noqa: E501
        :rtype: str
        """
        return self._device_id

    @device_id.setter
    def device_id(self, device_id):
        """Sets the device_id of this V2monitoringsitetwampsiteIdSelectors.


        :param device_id: The device_id of this V2monitoringsitetwampsiteIdSelectors.  # noqa: E501
        :type: str
        """

        self._device_id = device_id

    @property
    def interface_name(self):
        """Gets the interface_name of this V2monitoringsitetwampsiteIdSelectors.  # noqa: E501


        :return: The interface_name of this V2monitoringsitetwampsiteIdSelectors.  # noqa: E501
        :rtype: str
        """
        return self._interface_name

    @interface_name.setter
    def interface_name(self, interface_name):
        """Sets the interface_name of this V2monitoringsitetwampsiteIdSelectors.


        :param interface_name: The interface_name of this V2monitoringsitetwampsiteIdSelectors.  # noqa: E501
        :type: str
        """

        self._interface_name = interface_name

    @property
    def type(self):
        """Gets the type of this V2monitoringsitetwampsiteIdSelectors.  # noqa: E501


        :return: The type of this V2monitoringsitetwampsiteIdSelectors.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this V2monitoringsitetwampsiteIdSelectors.


        :param type: The type of this V2monitoringsitetwampsiteIdSelectors.  # noqa: E501
        :type: str
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V2monitoringsitetwampsiteIdSelectors, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V2monitoringsitetwampsiteIdSelectors):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
