from ..Math.Vec3 import Vec3
from .BaseMesh import BaseMesh as BaseMesh, Face as Face

class Obj(BaseMesh):
    def __init__(self) -> None: ...
    def load(self, file: str): ...
    @classmethod
    def from_file(cls, fname: str) -> Obj: ...
    def add_vertex(self, vert: Vec3) -> None: ...
    def add_vertex_colour(self, vert: Vec3, colour: Vec3) -> None: ...
    def add_normal(self, normal: Vec3) -> None: ...
    def add_uv(self, uv: Vec3) -> None: ...
    def add_face(self, face: Face) -> None: ...
    def save(self, filename: str) -> None: ...
