# This file was auto-generated by Fern from our API Definition.

import typing

EpisodeOfCareStatusHistoryStatus = typing.Union[
    typing.Literal[
        "planned",
        "waitlist",
        "active",
        "onhold",
        "finished",
        "cancelled",
        "entered-in-error",
    ],
    typing.Any,
]
