from setuptools import setup

setup(
    name="amgd",
    version="1.0.1",
    description="Adaptive Momentum Gradient Descent for Regularized Poisson Regression",
    long_description=open("README.md", encoding="utf-8").read(),
    long_description_content_type="text/markdown",
    author="Ibrahim Bakari, M. Revan Özkale",
    author_email="2020913072@ogr.cu.edu.tr, mrevan@cu.edu.tr",
    url="https://github.com/elbakari01/amgd_package", 
    project_urls={
        "Bug Tracker": "https://github.com/elbakari01/amgd_package/issues", 
        "Documentation": "https://amgd-poisson.readthedocs.io", 
        "Source Code": "https://github.com/elbakari01/amgd_package", 
    },
    license="MIT",
    packages=["amgdoptimizer"],
    package_dir={"": "src"},
    python_requires=">=3.6",
    install_requires=[
        "numpy>=1.20.0",
        "scipy>=1.7.0",
        "scikit-learn>=1.0.0",
        "matplotlib>=3.3.0",
        "pandas>=1.3.0",
    ],
    extras_require={
        "dev": [
            "pytest>=6.0",
            "pytest-cov>=3.0",
            "black>=22.0",
            "flake8>=4.0",
            "mypy>=0.950",
            "pre-commit>=2.15",
        ],
        "docs": [
            "sphinx>=4.0",
            "sphinx-rtd-theme>=1.0",
            "sphinx-autodoc-typehints>=1.12",
            "nbsphinx>=0.8",
            "jupyter>=1.0",
        ],
        "benchmarks": [
            "seaborn>=0.11",
            "plotly>=5.0",
            "memory-profiler>=0.60",
        ],
    },
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Operating System :: OS Independent",
    ],
    keywords="machine learning poisson regression optimization sparsity regularization",
)