
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-05-30T17:32:57+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "52093ab5b1d44c69f306bd55eccaffa0546e8480",
 "version": "5.0.0a0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
