from setuptools import setup, find_packages

from autoai_scripts.data_preprocessing_scripts.encoding_scaling_scripts import encoding_script, scaling_script
from autoai_scripts.data_preprocessing_scripts.null_outlier_scripts import outlier_remover
from autoai_scripts.data_preprocessing_scripts.skewed_kurtosis_scripts import skewness_remover

from autoai_scripts.dataset_loader import loader
from autoai_scripts.dependency_importer import dependency_importer
from autoai_scripts.hyperparameter_tuning_scripts import random_search, grid_search
from autoai_scripts.plot_visualizations import exploratory_data_analysis, show_eval_plot
